import { ToastContainer } from "react-toastify";
import AuthWrapper from "@/components/AuthWrapper";
import Header from "@/components/Header";
import 'react-toastify/dist/ReactToastify.css';
import "@/globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <AuthWrapper>
    <html lang="en">
      <body className="bg-[#323437] ">  
        <div >
          <div className="m-5 p-5">
            <Header/>
          </div>
          <main className="p-4 mx-16">
            {children}
          </main>
        </div>
        <ToastContainer></ToastContainer>
      </body>
    </html>
    </AuthWrapper>
  );
}
